import React from "react";
import { Montserrat } from "next/font/google";

import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

const globalFont = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={globalFont.className}>{children}</body>
    </html>
  );
}
