"use client";

import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, theme } from "antd";
import ThemeWrapper from "./ThemeWrapper";

import "./global.css";

import { Montserrat } from "next/font/google";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js"
// };

const globalFont = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider theme={{ algorithm: theme.darkAlgorithm }}>
      <html lang="en">
        <body className={globalFont.className}>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </html>
    </ConfigProvider>
  );
}
